services:
  server:
    build: ./server
    ports:
      - "5050:5050"
    volumes:
      - ./server/static:/app/static

  sender:
    build: ./sender
    volumes:
      - ./data:/data
    depends_on:
      - server